language: java

jdk:
- openjdk8

sudo: required

services:
- docker

before_install:
- cd OpenGuitarStore/Install/dev
- docker-compose -p guitarstoredb up -d database
- docker build -t mahxwell/springconfig servers/01_springconfig
- docker-compose -p guitarstoredb up -d springconfig
- docker build -t mahxwell/eureka servers/02_eureka
- docker-compose -p guitarstoredb up -d eureka
- docker build -t mahxwell/zuul servers/03_zuul
- docker-compose -p guitarstoredb up -d zuul



script:
- cd ../../guitar
- mvn test
- cd ../guitar
- mvn test
- cd ../reservation
- mvn test
- cd ../review
- mvn test
- cd ../user
- mvn test
- cd ../docker/dev
- docker container stop zuul
- docker container stop eureka
- docker container stop springconfig
- docker container stop guitarstore_db
- docker rm guitarstoredb
- docker rm springconfig
- docker rm eureka
- docker rm zuul


notifications:
email: false
