language: java

jdk:
- openjdk8

sudo: required

services:
- docker

before_install:
- cd OpenGuitarStore/docker/dev

script:
- docker-compose -p guitarstoredb up -d database
- docker build -t mahxwell/eureka servers/02_eureka
- docker-compose -p guitarstoredb up -d eureka
- cd ../../guitar
- mvn test
- cd ../order
- mvn test
- cd ../reservation
- mvn test
- cd ../review
- mvn test
- cd ../user
- mvn test
- cd ../docker/dev
- docker container stop eureka
- docker container stop guitarstore_db
- docker rm guitarstore_db
- docker rm eureka

after_success:
- mvn --file pom.xml cobertura:cobertura coveralls:report -P test-guitar

notifications:
email: false
