language: java

jdk:
- openjdk8

sudo: required

services:
- docker

before_install:
- cd OpenGuitarStore/Install/docker/dev
- docker-compose -p guitarstoredb up -d database

script:
- cd ../../guitar
- mvn test
- cd ../guitar
- mvn test
- cd ../reservation
- mvn test
- cd ../review
- mvn test
- cd ../user
- mvn test
- cd ../docker/dev
- docker container stop libguitarstoredbrary_db
- docker rm library_web_service
- docker rm guitarstoredb


notifications:
email: false
