language: java

jdk:
- openjdk8

sudo: required

services:
- docker

before_install:
- cd OpenGuitarStore/docker/dev
- docker-compose -p guitarstoredb up -d database
- docker build -t mahxwell/eureka servers/02_eureka
- docker-compose -p guitarstoredb up -d eureka



script:
- cd ../../guitar
- mvn test
- cd ../docker/dev
- docker container stop eureka
- docker container stop guitarstore_db
- docker rm guitarstoredb
- docker rm eureka


notifications:
email: false
