version: '3.1'
services:
  database:
    image: postgres:10.3-alpine
    container_name: guitarstore_db
    restart: always
    hostname: 127.0.0.1
    volumes:
      - "./init/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    ports:
      -  "5432:5432"
    environment:
      - POSTGRES_DB=guitarstoredb
      - POSTGRES_USER=guitarstoreuser
      - POSTGRES_PASSWORD=toto
  springconfig:
    image: mahxwell/springconfig
    container_name: springconfig
    ports:
      -  "9101:9101"
  eureka:
    image: mahxwell/eureka
    container_name: eureka
    ports:
      -  "9102:9102"
  zuul:
    image: mahxwell/zuul
    container_name: zuul
    ports:
      -  "9004:9004"
  springadmin:
    image: mahxwell/springadmin
    container_name: springadmin
    ports:
      -  "9105:9105"
  batch:
    image: mahxwell/batch
    container_name: batch
  user:
    image: mahxwell/user
    container_name: user
    ports:
      -  "9003:9003"     
  guitar:
    image: mahxwell/guitar
    container_name: guitar
    ports:
      -  "9002:9002"    
  order:
    image: mahxwell/order
    container_name: order
    ports:
      -  "9005:9005"    
  reservation:
    image: mahxwell/reservation
    container_name: reservation
    ports:
      -  "9007:9007"    
  review:
    image: mahxwell/review
    container_name: review
    ports:
      -  "9008:9008"