version: '3.1'
services:
  database:
    image: postgres:10.3-alpine
    container_name: guitarstore_db
    restart: always
    hostname: 127.0.0.1
    volumes:
      - "./init/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    ports:
      -  "5432:5432"
    environment:
      - POSTGRES_DB=guitarstoredb
      - POSTGRES_USER=guitarstoreuser
      - POSTGRES_PASSWORD=toto